management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Default logging configuration for all services
logging:
  level:
    root: INFO
    com.evoting: DEBUG

# JWT Configuration (Global)
jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 3600000 # 1 hour
  refresh-expiration: 86400000 # 24 hours
